WIP: Auto migration to swift 3
netguru/ResponseDetective pull request #18
Opened 2017-01-22 14:58 UTC by serejahh

2017-01-26 08:34 UTC, akashivskyy commented
Hi @serejahh! How is the progress going? Maybe you could use some help? 😉

2017-01-26 18:41 UTC, serejahh commented
Hi @akashivskyy. I hope I'll finish 2 step on the weekend. If you have time, let's finish it together 😄

2017-01-26 21:05 UTC, akashivskyy commented
I'm happy to help! 😊

I created a `feature/swift-3-dev` branch so that we can collaborate without touching `develop`. You can re-target (close and one another) this pull request to `feature/swift-3-dev` and we'll work together on stage 2. 😉

2017-01-27 10:22 UTC, akashivskyy commented
Nevermind that reopening, seems like I can change the base just like that. 😄

2017-01-28 20:54 UTC, serejahh commented
That's great! I've reviewed API and I can't say it doesn't follow. I just changed one thing

2017-01-28 20:59 UTC, serejahh commented
About tests:
1. I've fixed tests for JSONDeserializer, but the solution doesn't look good 😿 . Please have a look at https://github.com/netguru/ResponseDetective/pull/18/commits/a3e67c5b29109cc1ba3b80e4396a7a87bc044760
2. What would your suggestion be for tests which compare buffer output just by comparing strings (I mentioned it in #13) ?

2017-01-29 15:02 UTC, akashivskyy commented
As for conforming to [Swift 3's API Design Guidelines](https://swift.org/documentation/api-design-guidelines/), I see lots of places that can be improved in addition to changes in 707d1ff.

As for fixing `JSONBodyDeserializer` tests, I think your solution would be temporarily okay, just remember to **use tabs, not spaces** as we follow [GitHub's Style Guide](https://github.com/github/swift-style-guide) (I will put a link to that in README and CONTRIBUTING files).

As for fixing the buffer comparison tests, I think this is out of scope of this superb pull request. I'll need to think that over. 😉

Let me know if this is ready for in-depth code review. ✨

2017-01-29 20:27 UTC, serejahh commented
Oh, sorry. I've just fixed it ;)

I believe you can review and merge it (to be able to commit your change)

2017-01-29 20:49 UTC, akashivskyy requested changes
This looks very very good! 👍

In addition to the comments below, could you also update `README.md` to reflect the changes you've made? 😊

2017-01-29 20:49 UTC, akashivskyy commented on ResponseDetective.xcodeproj/project.pbxproj
> +				SWIFT_VERSION = 3.0;
Please remove these `SWIFT_VERSION` settings from the project file itself (by hitting backspace in "Build Settings" list) and update the value in [ResponseDetective-Common.xcconfig](https://github.com/netguru/ResponseDetective/blob/develop/Configuration/ResponseDetective-Common.xcconfig) instead.

2017-01-29 20:49 UTC, akashivskyy commented on Sources/BufferOutputFacility.swift
> +	public fileprivate(set) var requestRepresentations: [RequestRepresentation] = []
Let's use `private` if possible _(this affects other `fileprivate`s as well)_.

2017-01-29 20:49 UTC, akashivskyy commented on ResponseDetective.playground/Contents.swift
> +session.dataTask(with: request).resume()
Thanks for remembering about the playground! ✨

2017-01-29 20:49 UTC, akashivskyy commented on Tests/JSONBodyDeserializerSpec.swift
> +                let actualJSON = try! JSONSerialization.jsonObject(with: actualData, options: []) as! [String: Any]
You forgot to change spaces to tabs here... 🙈

2017-01-29 20:49 UTC, akashivskyy commented on Tests/ResponseDetectiveSpec.swift
> +                            let string = url.absoluteString
And here as well (tabs). 😄

2017-01-30 06:36 UTC, serejahh commented on Tests/JSONBodyDeserializerSpec.swift
> +                let actualJSON = try! JSONSerialization.jsonObject(with: actualData, options: []) as! [String: Any]
Damn! Github diff didn't show

2017-01-30 06:41 UTC, serejahh commented on Sources/BufferOutputFacility.swift
> +	public fileprivate(set) var requestRepresentations: [RequestRepresentation] = []
Why do you prefer `private` over `fileprivate`? I love to use extensions in ways [Natasha The Robot](https://www.natashatherobot.com/using-swift-extensions/) described. In this case you need `fileprivate`

2017-01-30 06:44 UTC, serejahh commented on ResponseDetective.xcodeproj/project.pbxproj
> +				SWIFT_VERSION = 3.0;
![image](https://cloud.githubusercontent.com/assets/2575555/22414454/426f2f46-e6c8-11e6-882a-76b4fa44de6e.png)
Looks dangerous 😄

2017-01-30 09:24 UTC, akashivskyy commented on Sources/BufferOutputFacility.swift
> +	public fileprivate(set) var requestRepresentations: [RequestRepresentation] = []
Yes, but I don't see any extensions. 😉 

I just prefer the most restrictive access modifier – if there are no extensions, there is nothing that justifies them to be `fileprivate`.

2017-01-30 09:25 UTC, akashivskyy commented on ResponseDetective.xcodeproj/project.pbxproj
> +				SWIFT_VERSION = 3.0;
As it should. 😄

2017-01-30 09:27 UTC, akashivskyy approved these changes
Great work! 🚢

2017-01-30 09:28 UTC, merged